language: csharp
solution: FilippSystem.sln
mono: none
dotnet: 3.1.302
script:
 - dotnet restore
 - dotnet build
 - dotnet test
 install:
  - nuget restore FilippSystem.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release FilippSystem.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
