version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    
    steps:
      - checkout
      - run:
          name: restore packages
          command:
            dotnet restore
      - run:
          name: test app
          command:
            dotnet test
      - run:
          name: build app
          command:
            dotnet build
